[general]
live_config_reload = true
import = ["~/.config/alacritty/rose-pine-dawn.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
startup_mode = "Maximized"
title = "Terminal"
option_as_alt = "Both"
padding = { x = 5, y = 2 }

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 14
offset = { x = -1, y = 1 }
