gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
  showBottomLine: false
  filterMode: "fuzzy"
  commandLogSize: 3
  showRandomTip: false
  theme:
    activeBorderColor:
      - "#d7827e"
      - bold
    inactiveBorderColor:
      - "#6c6f85"
    optionsTextColor:
      - "#286983"
    selectedLineBgColor:
      - "#dfdad9"
    cherryPickedCommitBgColor:
      - "#dfdad9"
    cherryPickedCommitFgColor:
      - "#907aa9"
    unstagedChangesColor:
      - "#b4637a"
    defaultFgColor:
      - "#575279"
    searchingActiveBorderColor:
      - "#ea9d34"
  authorColors:
    "*": "#907aa9"
git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --paging=never --features="hoopoe" --syntax-theme="GitHub"
  commitPrefix:
    - pattern: "^(\\w+-\\d+).*"
      replace: "$1: "
    - pattern: "^(\\w+)-.*"
      replace: "$1: "
os:
  editPreset: "nvim"
