gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
  showBottomLine: false
  filterMode: "fuzzy"
  commandLogSize: 3
  showRandomTip: false
  theme:
    activeBorderColor:
      - green # Pine
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan # Rose
      - bold
    optionsTextColor:
      - blue # Foam
    selectedLineBgColor:
      - default
      - bold
      - underline
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - default
    cherryPickedCommitBgColor:
      - cyan # Rose
    markedBaseCommitFgColor:
      - blue # Foam
    markedBaseCommitBgColor:
      - yellow # Gold
    unstagedChangesColor:
      - red # Love
    defaultFgColor:
      - default
  authorColors:
    "*": magenta # Iris
git:
  overrideGpg: true
  commitPrefix:
    - pattern: "^(\\w+-\\d+).*"
      replace: "$1: "
    - pattern: "^(\\w+)-.*"
      replace: "$1: "
os:
  editPreset: "nvim"
